### ISSUE TITLE
The link in the description is dead

### ISSUE THREAD

**Issue by Shamrock-Frost** [ravichugh/djs#1]
http://people.cs.uchicago.edu/~rchugh/djs doesn't appear to be an existing site.

**Comment by schw1804** [comment]
And neither it nor its predecessor at www.ravichugh.com/djs is archived in the Wayback Machine.

**Comment by ravichugh** [comment]
Oops, sorry. I have that old page saved, but there's nothing interesting: it just contains links to things that can be found on my webpage (POPL 2012 and OOPSLA 2012 papers and a SoCal 2011 poster) and links to a few commits in this repo.
